# Generated by Django 5.2.8 on 2025-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='foto_placa',
        ),
        migrations.AlterField(
            model_name='servico',
            name='foto_local_servico',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto_carro',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
