# Generated by Django 5.2.8 on 2026-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_remove_veiculo_foto_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='obs_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Veículo'),
        ),
    ]
