# Generated by Django 5.2.8 on 2026-01-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_veiculo_obs_gerais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='observacao_servico',
            field=models.TextField(blank=True, null=True, verbose_name='Observação para o Cliente'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(verbose_name='O que foi feito no serviço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.mecanico', verbose_name='Mecânico Responsável'),
        ),
    ]
